### PR TITLE
Update for 0.16

### PR DESCRIPTION
**Pull request by mgold**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Why not just move the upper bounds? Moving the lower bounds is unwarranted if there are no syntax changes or anything else that would prevent the package from continuing to work with older Elm and older `core`!

**Comment by mgold** [comment]
Fine. I'm still suspicious of doing this, yes despite any evidence. I'd rather certainly exclude 0.15 users (of which there are none, or they can use the old version) than risk anything going wrong for 0.16.

**Comment by jvoigtlaender** [comment]
I'm strongly opposed to overconstraining. People like to complain about "cabal hell", when in reality most often the cause is not `cabal` the tool, but people (sometimes the same people that do the complaining) not using the tool correctly. For semantics versioning to have a chance to find the best solution, people should give accurate bounds. If there is no reason to move a bound, it should not be moved. If Elm ever moves from dozens to hundreds or thousands of packages in the repository, practice like overconstraining will be very hurtful. Better not to develop that habit. (IMHO)

The excuse "they can use the old version" is moot, I'm sure you are away. What if tomorrow we add a new function to the package? It will never become available to those "old users", because a lower bound was moved for no real reason at all.

**Comment by mgold** [comment]
Okay, that sounds more reasonable, thank you for the explanation. Would you like to merge?

**Pull request merged**
